# Generated by Django 4.2.5 on 2023-09-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='creator_following',
            field=models.ManyToManyField(related_name='creator_followers', to='users_api.creatorprofile'),
        ),
    ]
