# Generated by Django 4.2.5 on 2024-05-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
