# Generated by Django 4.2.5 on 2024-02-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='creator_logo',
            field=models.ImageField(blank=True, default='default/creator_default.jfif', upload_to='creatorProfile/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, default='default/user_default.jpg', upload_to='userProfile/%Y/%m/%d/'),
        ),
    ]
