# Generated by Django 4.2.5 on 2024-05-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
