# Generated by Django 4.2.5 on 2023-10-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user_profile',
            new_name='user',
        ),
    ]
