# Generated by Django 4.2.5 on 2024-05-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_creatorprofile_total_likes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creatorprofile',
            index=models.Index(fields=['total_likes'], name='users_api_c_total_l_6e3496_idx'),
        ),
    ]
