# Generated by Django 4.2.5 on 2023-09-25 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_creatorprofile_creator_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='followers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_api.userprofile'),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='creator_following',
            field=models.ManyToManyField(blank=True, null=True, related_name='creator_followers', to='users_api.creatorprofile'),
        ),
    ]
