# Generated by Django 4.2.5 on 2023-09-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0003_creatorprofile_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='creator_following',
            field=models.ManyToManyField(blank=True, related_name='creator_followers', to='users_api.creatorprofile'),
        ),
    ]
