# Generated by Django 4.2.5 on 2023-09-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0003_creatorprofile_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_commonuser',
            field=models.BooleanField(default=True),
        ),
    ]
