# Generated by Django 4.2.5 on 2024-03-09 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0003_delete_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatorprofile',
            old_name='company_description',
            new_name='biography',
        ),
    ]
