# Generated by Django 4.2.5 on 2024-07-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_alter_creatorprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='background_image',
            field=models.ImageField(blank=True, default='default/default.jpg', upload_to='creatorProfile/I%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='creator_logo',
            field=models.ImageField(blank=True, default='default/default.jpg', upload_to='creatorProfile/%Y/%m/%d/'),
        ),
    ]
