# Generated by Django 4.2.5 on 2023-09-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_creatorprofile_is_creator_userprofile_is_commonuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_commonuser',
        ),
    ]
