# Generated by Django 4.2.5 on 2023-09-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_alter_creatorprofile_creator_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorprofile',
            name='followers',
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='users_api.userprofile'),
        ),
    ]
