# Generated by Django 5.0.7 on 2024-07-28 16:57

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('users_api', '0005_creatorprofile_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='interests',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
