# Generated by Django 4.2.5 on 2023-09-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0005_remove_creatorprofile_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorprofile',
            name='followers',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following_creators',
            field=models.ManyToManyField(blank=True, related_name='user_followers', to='users_api.creatorprofile'),
        ),
    ]
