# Generated by Django 5.0.7 on 2024-08-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0006_creatorprofile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='favorite_quote',
            field=models.TextField(blank=True, max_length=70),
        ),
    ]
