# Generated by Django 4.2.5 on 2023-09-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0006_remove_creatorprofile_is_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_creator',
            field=models.BooleanField(default=False, help_text='Specify whether user is creator or not. Default is set to False'),
        ),
    ]
