# Generated by Django 4.2.5 on 2023-09-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0007_alter_customuser_is_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
