# Generated by Django 5.0.7 on 2024-08-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0007_creatorprofile_favorite_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='favorite_quote',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
