# Generated by Django 4.2.5 on 2023-09-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0008_alter_creatorprofile_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
