# Generated by Django 4.2.5 on 2023-11-25 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created'], name='comment_sys_created_894a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['target_ct', 'target_id'], name='comment_sys_target__b9b095_idx'),
        ),
    ]
