# Generated by Django 4.2.5 on 2024-05-08 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
        ('comment_system', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_posted'], 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comment_sys_created_894a0e_idx',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='date_posted',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comment_system.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users_api.creatorprofile'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-date_posted'], name='comment_sys_date_po_493377_idx'),
        ),
    ]
