# Generated by Django 5.0.7 on 2024-08-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_system', '0003_alter_comment_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_posted'], 'verbose_name_plural': 'Comments'},
        ),
    ]
