# Generated by Django 4.2.5 on 2024-05-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_users',
            field=models.ManyToManyField(blank=True, related_name='current_rooms', to='users_api.creatorprofile'),
        ),
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='users_api.creatorprofile'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.room'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users_api.creatorprofile'),
        ),
    ]
