# Generated by Django 5.0.7 on 2024-08-10 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_message_date_remove_message_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_on']},
        ),
    ]
