# Generated by Django 4.2.5 on 2024-03-30 13:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_api', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField()),
                ('release_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Season',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=200, unique=True)),
                ('series_poster', models.ImageField(default='default/series.jpg', upload_to='series/posters/%Y/%m/')),
                ('synopsis', models.TextField(max_length=500)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_created', to='users_api.creatorprofile', verbose_name='creator')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_series', to='users_api.userprofile')),
                ('likes', models.ManyToManyField(blank=True, related_name='series_like', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('synopsis', models.TextField(blank=True, max_length=300)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, default='default/singles.jfif', upload_to='singles/poster/%Y/%m/')),
                ('video_file', models.FileField(upload_to='singles/video/%Y/%m/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users_api.creatorprofile')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Video Content',
                'verbose_name_plural': 'Video Contents',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('synopsis', models.TextField(blank=True, max_length=300)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, default='default/singles.jfif', upload_to='singles/poster/%Y/%m/')),
                ('content', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users_api.creatorprofile')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Text Content',
                'verbose_name_plural': 'Text Contents',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('episode_title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=700, null=True)),
                ('episode_release_date', models.DateField(auto_now_add=True)),
                ('publish', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(blank=True, default='default/story.jfif', upload_to='stories/thumbnails/%Y/%m/')),
                ('content', models.TextField()),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_stories', to='users_api.userprofile')),
                ('likes', models.ManyToManyField(blank=True, related_name='%(class)s_like', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_api.season')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='anime_api.series')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', to='anime_api.series'),
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('synopsis', models.TextField(blank=True, max_length=300)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('illustration', models.ImageField(upload_to='singles/designs/%Y/%m/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users_api.creatorprofile')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Design/Illustration Content',
                'verbose_name_plural': 'Design/Illustration Contents',
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('episode_title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=700, null=True)),
                ('episode_release_date', models.DateField(auto_now_add=True)),
                ('publish', models.BooleanField(default=True)),
                ('anime_thumbnail', models.ImageField(blank=True, default='default/anime.jfif', upload_to='animations/thumbnails/%Y/%m/')),
                ('video_file', models.FileField(upload_to='animations/video/%Y/%m/')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_animes', to='users_api.userprofile')),
                ('likes', models.ManyToManyField(blank=True, related_name='%(class)s_like', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_api.season')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='anime_api.series')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Animation',
                'verbose_name_plural': 'Animations',
            },
        ),
    ]
