# Generated by Django 4.2.5 on 2023-10-04 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
        ('anime_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_created', to='users_api.creatorprofile', verbose_name='creator'),
        ),
    ]
