# Generated by Django 4.2.5 on 2023-09-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='epiode_number',
            new_name='episode_number',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='epiode_number',
            new_name='episode_number',
        ),
    ]
