# Generated by Django 4.2.5 on 2023-09-27 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='likes',
            field=models.ManyToManyField(related_name='%(class)s_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='series',
            name='likes',
            field=models.ManyToManyField(related_name='series_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='likes',
            field=models.ManyToManyField(related_name='%(class)s_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
