# Generated by Django 4.2.5 on 2023-10-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='series',
        ),
        migrations.RemoveField(
            model_name='story',
            name='series',
        ),
    ]
