# Generated by Django 4.2.5 on 2023-10-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='file',
            field=models.FileField(upload_to='animations/video/%Y/%m/', verbose_name='video file'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='animations/thumbnails/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_poster',
            field=models.ImageField(upload_to='series/posters/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='stories/thumbnails/%Y/%m/'),
        ),
    ]
