# Generated by Django 4.2.5 on 2023-11-25 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime_api', '0001_initial'),
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_api.season'),
        ),
        migrations.AddField(
            model_name='story',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='anime_api.series'),
        ),
        migrations.AddField(
            model_name='series',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_created', to='users_api.creatorprofile', verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='series',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='series_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', to='anime_api.series'),
        ),
        migrations.AddField(
            model_name='anime',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime_api.season'),
        ),
        migrations.AddField(
            model_name='anime',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='anime_api.series'),
        ),
    ]
