# Generated by Django 4.2.5 on 2023-09-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0002_rename_epiode_number_anime_episode_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='epidose_title',
            new_name='episode_title',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='epidose_title',
            new_name='episode_title',
        ),
    ]
