# Generated by Django 4.2.5 on 2024-04-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
        ('anime_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_series', to='users_api.creatorprofile'),
        ),
    ]
