# Generated by Django 4.2.5 on 2023-09-27 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime_api', '0002_anime_likes_series_likes_story_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='series',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='series_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
