# Generated by Django 4.2.5 on 2023-10-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0003_alter_series_series_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='slug',
        ),
    ]
