# Generated by Django 4.2.5 on 2023-11-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0003_anime_tags_series_tags_story_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='thumbnail',
            new_name='anime_thumbnail',
        ),
    ]
