# Generated by Django 4.2.5 on 2024-05-05 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0003_alter_series_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_season', to='anime_api.season'),
        ),
        migrations.AlterField(
            model_name='story',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_season', to='anime_api.season'),
        ),
    ]
