# Generated by Django 4.2.5 on 2023-09-11 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0003_rename_epidose_title_anime_episode_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episode_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='story',
            name='episode_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
