# Generated by Django 4.2.5 on 2024-05-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_alter_creatorprofile_slug'),
        ('anime_api', '0004_anime_slug_design_slug_series_slug_text_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='%(class)s_like', to='users_api.creatorprofile'),
        ),
        migrations.AlterField(
            model_name='writtenstory',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='%(class)s_like', to='users_api.creatorprofile'),
        ),
    ]
