# Generated by Django 4.2.5 on 2023-09-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0004_alter_anime_episode_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='animations/thumbnails/%Y/%m/%d'),
        ),
    ]
