# Generated by Django 4.2.5 on 2023-10-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0004_remove_series_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='file',
            field=models.FileField(upload_to='animations/video/%Y/%m/'),
        ),
    ]
