# Generated by Django 4.2.5 on 2023-11-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0004_rename_thumbnail_anime_anime_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='file',
            new_name='video_file',
        ),
    ]
