# Generated by Django 4.2.5 on 2024-05-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0004_alter_anime_season_alter_story_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='type',
            field=models.CharField(choices=[('Anime', 'Animation'), ('Story', 'Story')], default='Anime', max_length=10),
        ),
    ]
