# Generated by Django 4.2.5 on 2023-09-11 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0005_alter_anime_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='series_poster',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='series/posters/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
