# Generated by Django 4.2.5 on 2024-05-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_alter_creatorprofile_slug'),
        ('anime_api', '0005_alter_anime_likes_alter_writtenstory_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_like', to='users_api.creatorprofile'),
        ),
        migrations.AlterField(
            model_name='writtenstory',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_like', to='users_api.creatorprofile'),
        ),
    ]
