# Generated by Django 4.2.5 on 2023-11-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0005_rename_file_anime_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_thumbnail',
            field=models.ImageField(blank=True, default='default/anime.jpg', upload_to='animations/thumbnails/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_poster',
            field=models.ImageField(default='default/series.jpg', upload_to='series/posters/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/story.jpg', upload_to='stories/thumbnails/%Y/%m/'),
        ),
    ]
