# Generated by Django 4.2.5 on 2024-05-05 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_api', '0001_initial'),
        ('anime_api', '0005_season_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Story',
            new_name='WrittenStory',
        ),
    ]
