# Generated by Django 4.2.5 on 2024-05-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0006_rename_story_writtenstory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writtenstory',
            options={'verbose_name': 'Written Story', 'verbose_name_plural': 'Written Stories'},
        ),
        migrations.RenameField(
            model_name='season',
            old_name='type',
            new_name='obj_type',
        ),
    ]
