# Generated by Django 4.2.5 on 2024-01-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0006_alter_anime_anime_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-release_date'], 'verbose_name_plural': 'Season'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Series'},
        ),
    ]
