# Generated by Django 4.2.5 on 2023-09-11 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime_api', '0006_series_series_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_created', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='series',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
