# Generated by Django 4.2.5 on 2024-05-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
        ('anime_api', '0007_alter_writtenstory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_animes', to='users_api.creatorprofile'),
        ),
        migrations.AlterField(
            model_name='writtenstory',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_stories', to='users_api.creatorprofile'),
        ),
    ]
