# Generated by Django 4.2.5 on 2024-02-12 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_alter_creatorprofile_creator_logo_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('anime_api', '0007_alter_season_options_alter_series_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='singles/video/%Y/%m/')),
            ],
        ),
        migrations.AlterField(
            model_name='anime',
            name='anime_thumbnail',
            field=models.ImageField(blank=True, default='default/anime.jfif', upload_to='animations/thumbnails/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/story.jfif', upload_to='stories/thumbnails/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('synopsis', models.CharField(max_length=300)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, default='default/singles.jfif', upload_to='singles/poster/%Y/%m/')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('text', 'video')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singles', to='users_api.creatorprofile')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
        ),
    ]
