# Generated by Django 4.2.5 on 2023-09-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0007_alter_series_creator_alter_series_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
