# Generated by Django 4.2.5 on 2024-05-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
        ('anime_api', '0008_alter_anime_favorited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='likes',
            field=models.ManyToManyField(related_name='liked', to='users_api.creatorprofile'),
        ),
    ]
