# Generated by Django 4.2.5 on 2024-06-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0008_alter_design_likes_alter_text_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
