# Generated by Django 4.2.5 on 2024-05-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
        ('anime_api', '0009_text_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='likes',
            field=models.ManyToManyField(related_name='liked_illustration', to='users_api.creatorprofile'),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(related_name='liked_videos', to='users_api.creatorprofile'),
        ),
        migrations.AlterField(
            model_name='text',
            name='likes',
            field=models.ManyToManyField(related_name='liked_text', to='users_api.creatorprofile'),
        ),
    ]
