# Generated by Django 4.2.5 on 2024-06-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0009_season_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='episode_release_date',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='writtenstory',
            old_name='episode_release_date',
            new_name='release_date',
        ),
    ]
