# Generated by Django 4.2.5 on 2024-05-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
        ('anime_api', '0010_design_likes_video_likes_alter_text_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_like', to='users_api.creatorprofile'),
        ),
        migrations.AlterField(
            model_name='writtenstory',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_like', to='users_api.creatorprofile'),
        ),
    ]
