# Generated by Django 4.2.5 on 2024-06-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0010_rename_episode_release_date_anime_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='series_poster',
            field=models.ImageField(default='default/default.jpg', upload_to='series/posters/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='text',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/default.jpg', upload_to='singles/poster/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/default.jpg', upload_to='singles/poster/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='writtenstory',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/default.jpg', upload_to='stories/thumbnails/%Y/%m/'),
        ),
    ]
