# Generated by Django 4.2.5 on 2024-05-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
        ('anime_api', '0011_alter_anime_likes_alter_writtenstory_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='series_like', to='users_api.creatorprofile'),
        ),
    ]
