# Generated by Django 4.2.5 on 2024-06-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_alter_creatorprofile_slug'),
        ('anime_api', '0011_alter_series_series_poster_alter_text_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_design', to='users_api.creatorprofile'),
        ),
        migrations.AddField(
            model_name='text',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_text', to='users_api.creatorprofile'),
        ),
        migrations.AddField(
            model_name='video',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_video', to='users_api.creatorprofile'),
        ),
    ]
