# Generated by Django 4.2.5 on 2024-05-05 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0012_alter_series_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['release_date'], 'verbose_name_plural': 'Season'},
        ),
    ]
