# Generated by Django 5.0.7 on 2024-07-29 20:46

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0012_design_favorited_by_text_favorited_by_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('users_api', '0006_creatorprofile_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('title', models.CharField(max_length=150)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='singles/photography/%Y/%m/')),
                ('typeof', models.CharField(default='photography', max_length=6)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users_api.creatorprofile')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='photography', to='users_api.creatorprofile')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_photography', to='users_api.creatorprofile')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Photography',
                'verbose_name_plural': 'Photography',
            },
        ),
    ]
