# Generated by Django 4.2.5 on 2024-03-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0012_rename_thumbnail_story_story_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='story_thumbnail',
            new_name='thumbnail',
        ),
    ]
