# Generated by Django 4.2.5 on 2024-05-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0013_alter_season_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='anime_thumbnail',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='anime',
            name='typeof',
            field=models.CharField(default='anime', max_length=5),
        ),
        migrations.AddField(
            model_name='design',
            name='typeof',
            field=models.CharField(default='design', max_length=6),
        ),
        migrations.AddField(
            model_name='season',
            name='typeof',
            field=models.CharField(default='season', max_length=6),
        ),
        migrations.AddField(
            model_name='series',
            name='typeof',
            field=models.CharField(default='series', max_length=6),
        ),
        migrations.AddField(
            model_name='text',
            name='typeof',
            field=models.CharField(default='text', max_length=4),
        ),
        migrations.AddField(
            model_name='video',
            name='typeof',
            field=models.CharField(default='video', max_length=5),
        ),
        migrations.AddField(
            model_name='writtenstory',
            name='typeof',
            field=models.CharField(default='writtenstory', max_length=12),
        ),
    ]
