# Generated by Django 4.2.5 on 2024-03-09 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_rename_company_description_creatorprofile_biography'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('anime_api', '0015_design_alter_media_content_type_alter_media_synopsis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.RemoveField(
            model_name='design',
            name='design',
        ),
        migrations.AddField(
            model_name='design',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('text', 'video', 'design')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='design',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users_api.creatorprofile'),
        ),
        migrations.AddField(
            model_name='design',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='singles/designs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='design',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='synopsis',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/singles.jfif', upload_to='singles/poster/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='design',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('text', 'video', 'design')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='text',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users_api.creatorprofile'),
        ),
        migrations.AddField(
            model_name='text',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='synopsis',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/singles.jfif', upload_to='singles/poster/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='text',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('text', 'video', 'design')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='video',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users_api.creatorprofile'),
        ),
        migrations.AddField(
            model_name='video',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='synopsis',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/singles.jfif', upload_to='singles/poster/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='singles/video/%Y/%m/'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
