# Generated by Django 4.2.5 on 2024-03-09 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users_api', '0004_rename_company_description_creatorprofile_biography'),
        ('anime_api', '0016_alter_design_options_alter_text_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'design')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='design',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users_api.creatorprofile'),
        ),
        migrations.AlterField(
            model_name='design',
            name='illustration',
            field=models.ImageField(upload_to='singles/designs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='design',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='design',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='synopsis',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='design',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='text',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'design')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='text',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users_api.creatorprofile'),
        ),
        migrations.AlterField(
            model_name='text',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='text',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='synopsis',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='video',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'design')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='video',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='users_api.creatorprofile'),
        ),
        migrations.AlterField(
            model_name='video',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='synopsis',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='singles/video/%Y/%m/'),
        ),
    ]
