# Generated by Django 5.0.7 on 2024-08-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0016_alter_photography_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='writtenstory',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
