# Generated by Django 4.2.5 on 2024-03-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0017_alter_design_content_type_alter_design_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='synopsis',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='text',
            name='synopsis',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='video',
            name='synopsis',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
