# Generated by Django 5.0.7 on 2024-08-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0017_alter_anime_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='caption',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
