# Generated by Django 4.2.5 on 2024-03-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0018_alter_design_synopsis_alter_text_synopsis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='object_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='object_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='object_id',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
