# Generated by Django 4.2.5 on 2024-03-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0020_alter_design_object_id_alter_text_object_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.RemoveField(
            model_name='design',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='design',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='text',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='text',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='video',
            name='object_id',
        ),
    ]
