# Generated by Django 4.2.5 on 2024-03-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0021_alter_design_options_alter_text_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'verbose_name': 'Design/Illustration Content', 'verbose_name_plural': 'Design/Illustration Contents'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Text Content', 'verbose_name_plural': 'Text Contents'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video Content', 'verbose_name_plural': 'Video Contents'},
        ),
    ]
