# Generated by Django 4.2.5 on 2024-03-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0023_design_tags_text_tags_video_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='thumbnail',
        ),
    ]
