# Generated by Django 4.2.5 on 2024-03-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0024_remove_text_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='thumbnail',
        ),
    ]
