# Generated by Django 4.2.5 on 2024-03-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0025_remove_design_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/singles.jfif', upload_to='singles/poster/%Y/%m/'),
        ),
    ]
